### ISSUE TITLE
[BUG] Can't use --contaminants with Singularity image

### ISSUE THREAD

**Issue by nbat64** [gbouras13/hybracter#115]
Hello,

I am using Hybracter for chromosome and mostly plasmids of Bacteria on an HPC. As Mamba env did not work I am running it with a Singularity image (version 0.11.0). The pipeline work well, except when I try to indicate the lamda.fasta for removing Nanopore contaminants.

Here is the command tested:
```
singularity exec "$containerImage" \
hybracter hybrid \
--input hybracter_"${RUN}".csv \
--datadir "${LOCAL_WORK_DIR}" \
--min_length "${MINLENGTH}" \
--min_quality "${QSCOREONT}" \
--contaminants /soft/2019013/Logiciels/hybracter/lambda.fasta \
--subsample_depth "${SUBSAMPLE}" \
--min_depth "${MINDEPTH}" \
--depth_filter 0.25 \
--flyeModel "--nano-hq" \
--extra_params_flye "--asm-coverage 50" \
--logic "${LOGIC}" \
--auto \
--medaka_override \
--medakaModel "${MEDAKA}" \
--threads "${THREADS}" \
--output "${RUN}"_output/
```
Here is the error message from Snakemake:

```
snakemake -s /opt/miniforge3/lib/python3.12/site-packages/hybracter/workflow/hybrid.smk --configfile 20241217_Camille_bar1-8_7ng_output/config.yaml --jobs 96 --use-conda --conda-prefix /opt/miniforge3/lib/python3.12/site-packages/hybracter/workflow/conda --rerun-incomplete --printshellcmds --nolock --show-failed-logs --conda-frontend conda
Config file /opt/miniforge3/lib/python3.12/site-packages/hybracter/workflow/../config/config.yaml is extended by additional config specified via the command line.
You have provided a host genome file lamba that is not a FASTA file.
[2024:12:26 18:24:05] ERROR: Snakemake failed
```
I thied aslo with the argument ``` --contaminants lambda``` I have the same error.

How to run contaminants with the .sif?

Thanks a lot for the help and yours pipelines!

regards

Nicolas

**Comment by gbouras13** [comment]
Hi @nbat64,

Turns out this appears to be a general issue with `--contaminants` 

This also failed for me in a conda environment.

`hybracter test-hybrid -t 24 -o test_hybrid --contaminants hybracter/contaminant_genomes/lambda.fasta`

Thanks for picking this up - will try and fix it shortly.

George

**Comment by gbouras13** [comment]
Specifically, there are 2 issues 

1) using `--lambda` was broken at line 35 in `remove_contaminants.smk` (`get_input_lr_fastqs` function)
2) specifying a FASTA file with `--contaminants` was broken due to the `is_fasta_file` function in `functions.smk`, which only accounted for .gz files, not for plain FASTA.

**Comment by nbat64** [comment]
Hi George,

Sorry I did not test it sooner, but unfortunately I still have a crash using the option ```--contaminants lamba``` with singularity image for the version 0.11.2

Here is the error message:
```
Building DAG of jobs...
Your conda installation is not configured to use strict channel priorities. This is however important for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
Creating conda environment /opt/miniforge3/lib/python3.12/site-packages/hybracter/workflow/envs/contaminants.yaml...
Traceback (most recent call last):

  File "/opt/miniforge3/lib/python3.12/site-packages/snakemake/cli.py", line 2156, in args_to_api
    dag_api.execute_workflow(

  File "/opt/miniforge3/lib/python3.12/site-packages/snakemake/api.py", line 597, in execute_workflow
    workflow.execute(

  File "/opt/miniforge3/lib/python3.12/site-packages/snakemake/workflow.py", line 1168, in execute
    self.dag.create_conda_envs()

  File "/opt/miniforge3/lib/python3.12/site-packages/snakemake/dag.py", line 468, in create_conda_envs
    env.create(self.workflow.dryrun)

  File "/opt/miniforge3/lib/python3.12/site-packages/snakemake/deployment/conda.py", line 629, in create
    out = create_env(env_file, filetype="yaml")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/miniforge3/lib/python3.12/site-packages/snakemake/deployment/conda.py", line 555, in create_env
    copy_permission_safe(env_file, target_env_file)

  File "/opt/miniforge3/lib/python3.12/site-packages/snakemake/common/__init__.py", line 373, in copy_permission_safe
    shutil.copy(src, dst)

  File "/opt/miniforge3/lib/python3.12/shutil.py", line 435, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)

  File "/opt/miniforge3/lib/python3.12/shutil.py", line 262, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^

OSError: [Errno 30] Read-only file system: '/opt/miniforge3/lib/python3.12/site-packages/hybracter/workflow/conda/b9a61600293b518bdd65eddb05e51e4d_.yaml'

[2025:02:18 17:44:54] ERROR: Snakemake failed
````
Without it is running correctly.

Best,

Nicolas
